### ISSUE TITLE
Network Monitoring Roadmap

### ISSUE THREAD

**Issue by OmarElfouly** [RustySnout/rustysnout#1]
### Base Goals
- [x] #3
- [x] Monitor multiple interfaces simultaneously
- [x] Sends notifications when a defined limit for a process or interface is reached
- [x] Shows packets sent/received from each interface and or process
- [x] Store data in a database such that it can be accessed after a reboot
- [x] Graphs bandwidth consumption against time
- [x] Configure tracking to allow it to synchronize with your bill such that it will show you how much you've consumed since the start of your cycle

- [x] DNS lookups for each connection
- [x] Provides the user with the current, average, min, and max bandwidth consumption of an interface and or process
- [x] Allows you to explore saved data by month, week, or day, extract the top N days, and filter by IP address, protocols, and ports.

### Stretch Goals

- [ ] Selects units dynamically such that a user will be able to see their numbers in a convenient manner
- [x] Both IPv4 and IPv6 support
- [ ] Produces reports on application and interface traffic
- [ ] Automatically detects interface bandwidth
- [ ] Graphical representation of all connections
- [ ] Multiple language support
- [ ] Search by keywords or patterns in packets
