### ISSUE TITLE
Network Control Roadmap

### ISSUE THREAD

**Issue by OmarElfouly** [RustySnout/rustysnout#2]
### Base Goal

- [x] Define the throttle (in terms of bandwidth) for a process before it is created
- [x] Define the throttle for an interface
- [x] Define the throttle for a connection according to destination ip

### Stretch Goal

- [ ] Dynamically start throttling an already existing process
